version: '3.0'

services:
  rabbitmq:
    restart: always
    image: brender-rabbit
    container_name: rabbitmq
    ports:
      # - "5672:5672"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
      - "8883:8883"
    # environment:
      # RABBIT_MANAGEMENT_PASSWORD: "admin"
      # RABBIT_MANAGEMENT_USER: "pass"
      # RABBITMQ_DEFAULT_USER: "rabbitmq"
      # RABBITMQ_DEFAULT_PASS: "rabbitmq"
      # - TZ=Asia/Shanghai
    tty: true
    volumes:
      # - "/etc/timezone:/etc/timezone:ro"
      # - "/etc/localtime:/etc/localtime:ro"
      - ./data:/var/lib/rabbitmq
      - ./conf/brender_rabbit.conf:/etc/rabbitmq/rabbitmq.config
      - ./conf/ssl/:/usr/local/rabbitmq/ssl/
    # command:  bash -c "date; sleep 5; rabbitmq-plugins enable rabbitmq_management; rabbitmq-server;"