version: '3.0'

services:
  rabbitmq:
    restart: always
    image: brender-rabbitmq:3.8.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
      - "15671:15671"
    # environment:
      # - TZ=Asia/Shanghai
    tty: true
    volumes:
      # - "/etc/timezone:/etc/timezone:ro"
      # - "/etc/localtime:/etc/localtime:ro"
      - ./data:/var/lib/rabbitmq
      - ./conf/brender_rabbit.conf:/etc/rabbitmq/rabbitmq.config
      - ./ssl:/usr/local/rabbitmq/ssl/
    # command:  bash -c "date; sleep 5; rabbitmq-plugins enable rabbitmq_management; rabbitmq-server;"